name: workflow

on:
  push:
    branches:
    - master
    
jobs:
  build:
    strategy:
      matrix:
        target: ['iOS', 'android']
        include:
          - target: android
            os: ubuntu-latest
            build_args: apk -t lib/main_prod.dart --flavor prod --release
            java-version: '11'
            firebase-distribute: true
          - target: iOS
            os: macos-latest
            build_args: ios --no-codesign
            firebase-distribute: false
    name: Build ${{ matrix.target }} app
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v2
      - if: ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: flutter format --set-exit-if-changed .
      - run: flutter test
      - name: build
        run: flutter build ${{ matrix.build_args }}
        env: 
          ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      - if: ${{ matrix.firebase-distribute }}
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_APP_ID_STAGING}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: /home/runner/work/todo_list/todo_list/build/app/outputs/flutter-apk/app-prod-release.apk 
